language: bash

matrix:
  include:
    #- os: linux
    #  dist: trusty
    #  sudo: required
    ## xcode7.3 = OS X 10.11 with bash-3.2.57(1)-release
    #- os: osx
    #  osx_image: xcode7.3
    #  sudo: required
    # xcode8.3 = OS X 10.12 with 
    - os: osx
      osx_image: xcode8.3
      sudo: required
  
branches:
  only:
    - master
    - develop
    - /^travis.*$/

notifications:
  email: true

install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tests/env/osx_dependencies.sh; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tests/env/linux_dependencies.sh; fi
#  - mysql -u root -e 'CREATE USER "travis"@"localhost";'
#  - mysql -u root -e 'CREATE DATABASE travis_magento;'
#  - mysql -u root -e 'GRANT ALL PRIVILEGES on travis_magento.* to "travis"@"localhost";'
  - brew update
  - brew install bash

#before_script:
#  - curl -Ls 'https://github.com/kward/shunit2/archive/master.zip' -o 'master.zip' && unzip -q 'master.zip' && rm 'master.zip'

script:
  - uname -av
  - sw_vers
  - system_profiler SPSoftwareDataType
  - bash --version
  - /usr/local/bin/bash --version
  #- tests/functional/m2_installation.sh
  #- tests/functional/deploy.sh
